items:
- uid: com.microsoft.applicationinsights._telemetry_client
  id: _telemetry_client
  parent: com.microsoft.applicationinsights
  children:
  - com.microsoft.applicationinsights._telemetry_client.TelemetryClient(TelemetryConfiguration)
  href: com.microsoft.applicationinsights._telemetry_client.yml
  langs:
  - csharp
  - vb
  name: TelemetryClient
  nameWithType: TelemetryClient
  fullName: com.microsoft.applicationinsights.TelemetryClient
  type: Class
  source:
    remote: &o0
      path: core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
      branch: master
      repo: https://github.com/Microsoft/ApplicationInsights-Java
    path: core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
    startLine: 46
  package: com.microsoft.applicationinsights
  summary: <p>Create an instance of this class to send telemetry to Azure Application Insights. General overview <ulink url="https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics">https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics</ulink></p>
  syntax: &o1
    content: public class TelemetryClient
  inheritance:
  - java.lang.Object
  inheritedMembers:
  - com.microsoft.applicationinsights._telemetry_client.getChannel()
- uid: com.microsoft.applicationinsights._telemetry_client.TelemetryClient(TelemetryConfiguration)
  id: TelemetryClient(TelemetryConfiguration)
  parent: com.microsoft.applicationinsights._telemetry_client
  href: com.microsoft.applicationinsights._telemetry_client.yml
  langs:
  - csharp
  - vb
  name: TelemetryClient(TelemetryConfiguration configuration)
  nameWithType: TelemetryClient.TelemetryClient(TelemetryConfiguration configuration)
  fullName: com.microsoft.applicationinsights.TelemetryClient.TelemetryClient(TelemetryConfiguration configuration)
  type: Constructor
  source:
    remote: *o0
    path: core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java
    startLine: 64
  package: com.microsoft.applicationinsights
  summary: <p>Initializes a new instance of the <xref href="com.microsoft.applicationinsights._telemetry_client" data-throw-if-not-resolved="false"></xref> class. Send telemetry with the specified configuration. </p>
  syntax:
    content: public TelemetryClient(TelemetryConfiguration configuration)
    parameters:
    - id: deviceId
      type: 4ebd16dc
references:
- uid: 4ebd16dc
  name: TimeSpan
  fullname: System.String
  fullname.csharp: foo
  fullname.vb: bar
  spec.csharp:
  - name: foo
    fullName: foo
    uid: foo
  spec.vb:
  - name: bar
    fullName: bar
    uid: bar
